config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root to: 'lists#index'
  resources :lists, only: [:show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list } # unique par
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)

    @bookmark.list = @list
    # connects bookmark and movies
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render '/show', status: :unprocessable_entity
    end
  end


  def destroy
    ## aqui queremos o id do bookmark e nao da list
    @bookmark = Bookmark.find(params[:id]) ## ja estamos no bookmarkers controller
    # só queremos identificar de forma geral o id do bookmark que queremos apagar,
    # para apagar nao interessa saber qual é a lista
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
    # After the deletion, it redirects the user to the show page of the list to which the deleted bookmark belonged
    # .list ou seja a lista onde estava esse bookmark, é como aceder a attributos


  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_list
    @list = List.find(params[:list_id]) ## the  GET show is in /lists/:id
    # para especificar em que lista o bookmark vai ser criado

    ## In the BookmarksController, when you're dealing with actions related to bookmarks that are scoped to a specific list,
    # you use params[:list_id] to identify the parent list.
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]

  def index
    @lists = List.all
    @new_list = List.new
  end

  def show
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  
  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to root_path
    else
      render :index, status: :unprocessable_entity
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body>

  <%# ################### %>
  <%# NavBar - UI kit Lewagon %>

  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
  <%# logo %>
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "My lists", root_path, class: "nav-link Mytext-color" %>
          </li>
          <%# <li class="nav-item">
            <%= link_to "Add list", "/index", class: "nav-link Mytext-color" %>
          <%# </li> %>

          <%# profile img and link %>
          <li class="nav-item dropdown myavatar">
            <%= image_tag "profile.png", class: " avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log in", "#", class: "dropdown-item" %>
              <%= link_to "Preferences", "#", class: "dropdown-item" %>
              <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>
  <%# end navbar################### %>


    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner banner-index">
  <div class="container text-center">
    <h1>All about movies!</h1>
    <p>Here you can organize your lists</p>
    <%# <a class="btn btn-flat" href="#">Apply now</a> %>
  </div>
</div>

<div class="cards m-4">
    <% @lists.each do |list| %>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))">
    <%= link_to list.name, list_path(list)%>
  </div>

    <% end %>

</div>

<div class="container m-5">
    <%= simple_form_for(@new_list) do |f| %>
      <%= f.input :name %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Add a new list", class: "btn btn-flat" %>
    <% end %>
</div>

app/views/lists/show.html.erb
<div class="banner" id="banner-show" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path(@list.photo.key) if @list.photo.present? %>')">
  <div class="container text-center">
    <h1><%= @list.name %></h1>
    <%# <a class="btn btn-flat" href="#">Apply now</a> %>
  </div>
</div>


<%# ## Card grid %>
<div class="cards m-5">
  <% @list.movies.each do |movie| %>
      <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>

<%# ## Card trip %>
  <div class="card-trip m-1">
    <img src= <%= movie.poster_url %> />
    <div class="card-trip-infos">
      <div>
        <h2><%= movie.title %></h2>
        <p><%= movie.overview %></p>
      </div><br>
      <h2 class="card-trip-pricing mx-2"><i class="fa-solid fa-star" style="color: #f9c206;"></i><%= movie.rating %></h2>
      <%= link_to "delete", bookmark_path(bookmark), class: "btn btn-warning mt--5", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this list?" } %>
    </div>
  </div>

  <% end %>
</div>


<%#  Form add new movie %>
  <div class="container m-5">
  <%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit "+ Add movie to this list", class: "btn btn-flat" %>
  <% end %>
</div>

  <div class="container m-5">
    <%= link_to "<- Back to Lists",  root_path, class: "btn btn-flat" %>
  </div>